#!/bin/sh

sbcl=sbcl
export TZ=GMT

cd "$(dirname "$0")" || exit 1

while true; do
	nice rlwrap -D -- "$sbcl" \
		--control-stack-size 1 \
		--disable-ldb --lose-on-corruption \
		--noinform --no-sysinit --no-userinit \
		--load loader-sbcl.lisp \
		&& exit 0
done
